name: UHC
version: 1.0
author: JuqnGOOD
main: uhc\UHC
api: 4.0.0
permissions:
  build.permission:
    default: op
  globalmute.bypass:
    default: op
  globalmute.command:
    default: op
  uhc.command:
    default: op